### PR TITLE
Adding Raspberry Pi article

### PR DESCRIPTION
**Pull request by SSaishruthi**

### CODE REVIEW

**Review by ptitzler — CHANGES_REQUESTED** [review]
What's the purpose of the icon?

**Comment by SSaishruthi** [comment]
I was thinking to have some icon to indicate a new blog or new announcement. Any other alternate suggestion is welcome. @ptitzler

**Comment by ptitzler** [comment]
I see. Then a "new" icon would be more intuitive but there's a general problem with tagging items manually because "new" is relative - is something new after 2 weeks or 4 months? IRL nobody is going to periodically go through the document (say every 3 months) and remove new tags. Therefore it's just a question of time until the tag becomes meaningless. One way to avoid this would be to add a date (e.g. mm/yy) to each item and sort by date in descending order. Or not do this at all.

**Comment by SSaishruthi** [comment]
@ptitzler 

I have removed the symbol. I will update after we decide on a way to highlight new announcements.

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
