### PR TITLE
Migrate max-status page

### PR DESCRIPTION
**Pull request by SSaishruthi**
1. Migrated https://github.com/CODAIT/max-status/blob/master/README.md to max-central-repo/max-model-status.md

2. Updated readme pointers for the same

### CODE REVIEW

**Comment by MLnick** [comment]
Only comment is for each model, we are listing distributions (node-red) but is that not duplicating what's already in the main readme of this repo?

**Comment by MLnick** [comment]
We probably also can remove the legacy trainable models - so that the list matches the one on the main readme.

Not sure if also want to split up into deployable and both as we do there? cc @ptitzler ?

**Comment by SSaishruthi** [comment]
@MLnick 

Thanks for pointing it out. Can we have distribution details only on the main readme, not on the max status page?

**Comment by MLnick** [comment]
> @MLnick
> 
> Thanks for pointing it out. Can we have distribution details only on the main readme, not on the max status page?

Yes, I think that makes more sense here

**Comment by ptitzler** [comment]
> Not sure if also want to split up into deployable and both
Probably not, because it requires the user to know whether a model is deployable or both. The intention of the status page was that one should be able to easily figure out what the [runtime] status is. For example, a user might want to know whether the long running instance is up. By further subdividing the list we'd make it harder to locate the model of interest

**Comment by MLnick** [comment]
Sure makes sense

**Comment by SSaishruthi** [comment]
- Removed legacy trainable models
- Removed trainable and deployable split
- No more distribution details in max-status page

Is this change ok?

**Review by MLnick — APPROVED** [review]

**Pull request merged**
